{% set name = "atomlite" %}
{% set version = "4.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomlite-{{ version }}.tar.gz
  sha256: cb1cef55b334621f8bd2bd452f9fc5296c61267a0ea538f15c901bf55dff202a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.11
    - rdkit
    - polars

test:
  imports:
    - atomlite

about:
  home: https://github.com/lukasturcani/atomlite
  summary: A SQLite chemical database.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
