{% set name = "atomlite" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomlite-{{ version }}.tar.gz
  sha256: 5ef95bfee976bc80347ef1f432f0107596e1c43f550e700803f0a4af1f7ffb8d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.11
    - rdkit
    - polars

test:
  imports:
    - atomlite

about:
  home: https://github.com/lukasturcani/atomlite
  summary: A SQLite chemical database.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
